### ISSUE TITLE
Mixtral inference example

### ISSUE THREAD

**Issue by casper-hansen** [shawntan/scattermoe#2]
Hi, I was reading the paper and it looks nice. Do you have any examples of using this with Mixtral? Perhaps you can share some of the benchmarking code from the paper?

**Comment by yikangshen** [comment]
Hi, you can find our mixtral implementation here in the example folder: https://github.com/shawntan/scattermoe/tree/main/examples/mixtral

**Comment by casper-hansen** [comment]
Hi @yikangshen, thanks for your example. It seems this is not able to run inference with the weights released by Mistral. How do we use Scatter MoE with models that have pretrained weights, e.g. for finetuning or running inference?

**Comment by shawntan** [comment]
I've written a conversion script that overrides `_load_pretrained_model` and converts the safetensor files to merge the experts into the ScatterMoE format. Try it and see if it works for you.

**Comment by shawntan** [comment]
Try out this  merge script and let me see how it works for you: https://github.com/shawntan/scattermoe/commit/0526612bd53f3fb4dc3418eaa2876c89efe5e4e2
